api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import StateCategoryViewSet,CollegeModelViewSet,ExamCategoryViewSet,ExamDetailsViewSet,HeaderMainViewSet,SubHeaderViewSet,SubHeaderHeadingViewSet,HeaderDetailsViewSet,NotificationViewSet

# Create a router and register the StateCategoryViewSet
router = DefaultRouter()
router.register(r'statecategory', StateCategoryViewSet, basename='statecategory')
router.register(r'college', CollegeModelViewSet, basename='college')
router.register(r'exam-category', ExamCategoryViewSet, basename='exam-category')
router.register(r'exam-details', ExamDetailsViewSet, basename='exam-details')
router.register(r'header-main', HeaderMainViewSet, basename='header-main')
router.register(r'sub-header', SubHeaderViewSet, basename='sub-header')
router.register(r'subheader-heading', SubHeaderHeadingViewSet, basename='subheader-heading')
router.register(r'header-details', HeaderDetailsViewSet, basename='header-details')
router.register(r'notifications', NotificationViewSet, basename='notifications')

urlpatterns = [   
    path('', include(router.urls)),  # DefaultRouter-generated endpoints
]

bsi_app/bsi_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bsi_app.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bsi_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bsi_app.urls')),
    path('api/', include('api.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bsi_app/models.py
from django.db import models
from ckeditor.fields import RichTextField

from django.utils import timezone


# Create your models here.
class ChatMessage(models.Model):
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=15)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.name}"
    
   
    
class ClientReview(models.Model):
    client_name = models.CharField(max_length=100, null=True, blank=True)
    client_image = models.ImageField(upload_to='client_images/', null=True, blank=True)
    designation = models.CharField(max_length=100, null=True, blank=True)
    review = models.TextField(null=True, blank=True)
    review_video = models.FileField(upload_to='review_videos/', null=True, blank=True)
    def __str__(self):
        return f"{self.client_name} - {self.designation}"
    

class Blog_Category(models.Model):
    category_name = models.CharField(max_length=100)
    blog_heading = models.CharField(max_length=100)
    date = models.DateField(null=True, blank=True)
    main_image = models.ImageField(upload_to='images/')
    status = models.BooleanField(default=False,help_text="0-default,1-Hidden")

    def __str__(self):
        return self.category_name
    
class Blog_Details(models.Model):
    category = models.ForeignKey(Blog_Category,on_delete=models.CASCADE)
    header_image = models.ImageField(upload_to='header_image/')
    blog_description = RichTextField(max_length=60000)
    blog_image = models.ImageField(upload_to='images/')
    status = models.BooleanField(default=False,help_text="0-default,1-Hidden")
    def __str__(self):
        return self.blog_description
    
class Client_Logo(models.Model):
    name = models.CharField(max_length=100,null=True,blank=True)
    logo = models.ImageField(upload_to='team_images/')

    def __str__(self):
        return self.name


class StateCategory(models.Model):
    state_name = models.CharField(max_length=100)
    
    state_image = models.ImageField(upload_to='images/')
    status = models.BooleanField(default=False,help_text="0-default,1-Hidden")

    def __str__(self):
        return self.state_name  
    

    
class CollegeModel(models.Model):
    category = models.ForeignKey(StateCategory,on_delete=models.CASCADE)
    college_name = models.CharField(max_length=200, null=True, blank=True)
    header_image = models.ImageField(upload_to='header_image/')
    place = models.CharField(max_length=200, null=True, blank=True)
    logo = models.ImageField(upload_to='college_logos/')
    college_image = models.ImageField(upload_to='college_image/')
    total_course = models.PositiveIntegerField(null=True, blank=True)
    rating = models.FloatField(null=True,blank=True)
    min_fee = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    max_fee = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    college_description  = models.TextField() 
    youtube_videos = models.URLField(max_length=200, unique=True, null=True, blank=True)
    college_brochure = models.FileField(upload_to='brochure/', null=True, blank=True)
    course_brochure = models.FileField(upload_to='brochure/', null=True, blank=True)
    more_details = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.college_name

    @property
    def total_fees_range(self):
        if self.min_fee and self.max_fee:
            return f"₹{self.min_fee} L - ₹{self.max_fee} L"
        return None
    
       

class FeaturedColleges(models.Model):
    college_details = models.ForeignKey(CollegeModel, on_delete=models.CASCADE, related_name='featured_in')
    college_logo = models.ImageField(upload_to='college_logos/')
    def __str__(self):
        return f"{self.college_details.college_name} (Featured)"

    class Meta:
        verbose_name = "Featured College"
        verbose_name_plural = "Featured Colleges"
        
    

class Course_Model(models.Model):
    PROFESSIONAL_COURSE = 'Professional'
    OPEN_COURSE = 'Open'
    COURSE_TYPE_CHOICES = [
        (PROFESSIONAL_COURSE, 'Professional Course'),
        (OPEN_COURSE, 'Open Course'),
    ]
    
    college = models.ForeignKey(CollegeModel, on_delete=models.CASCADE, related_name='courses')
    course_name = models.CharField(max_length=100, null=True, blank=True)
    course_type = models.CharField(max_length=15, choices=COURSE_TYPE_CHOICES, default=PROFESSIONAL_COURSE)
    course_description = models.TextField()
    course_fees = models.CharField(max_length=100, null=True, blank=True)
    course_duration = models.CharField(max_length=100, null=True, blank=True)
    seat_availability = models.CharField(max_length=100, null=True, blank=True)
    eligibility_criteria = models.CharField(max_length=100, null=True, blank=True)
    brochure = models.FileField(upload_to='brochure/', null=True, blank=True)
    course_videos = models.URLField(max_length=200, unique=True, null=True, blank=True)
    additional_details = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.course_name or 'Unnamed Course'

    class Meta:
        verbose_name = "Course"
        verbose_name_plural = "Courses"
        ordering = ['course_name']


class ExamModel(models.Model):
    exam_name = models.CharField(max_length=200)
    status = models.BooleanField(default=False,help_text="0-default,1-Hidden")
    
    def __str__(self):
        return self.exam_name


class ExamDetails(models.Model):
    exam = models.ForeignKey(ExamModel, on_delete=models.CASCADE)
    details = models.TextField()
    videos = models.URLField(max_length=200, unique=True, null=True, blank=True)
    exam_image = models.ImageField(upload_to='exam_image/', null=True, blank=True)
    sample_papers = models.FileField(upload_to='pdf/', null=True, blank=True)
    guide = models.FileField(upload_to='pdf/', null=True, blank=True)
    brochure = models.FileField(upload_to='brochure/', null=True, blank=True)
    more_details = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return f"{self.exam} Details"

    class Meta:
        verbose_name_plural = "Exam Details"


class ExamCategory(models.Model):
    OVERVIEW = 'Overview'
    QUESTION_PAPERS = 'Question Papers'
    DATE = 'Date'
    RESULTS = 'Results'
    CUT_OFF = 'Cut Off'
    ANSWER_KEY = 'Answer Key'
    ANALYSIS = 'Analysis'
    ADMIT_CARD = 'Admit Card'
    CENTER = 'Center'
    SYLLABUS = 'Syllabus'
    MOCK_TEST = 'Mock Test'
    
    EXAM_TYPE_CHOICES = [
        (OVERVIEW, 'Overview'),
        (QUESTION_PAPERS, 'Question Papers'),
        (DATE, 'Date'),
        (RESULTS, 'Results'),
        (CUT_OFF, 'Cut Off'),
        (ANSWER_KEY, 'Answer Key'),
        (ANALYSIS, 'Analysis'),
        (ADMIT_CARD, 'Admit Card'),
        (CENTER, 'Center'),
        (SYLLABUS, 'Syllabus'),
        (MOCK_TEST, 'Mock Test'),
    ]
    
    exam_name = models.ForeignKey('ExamModel', on_delete=models.CASCADE)
    exam_type = models.CharField(max_length=50, choices=EXAM_TYPE_CHOICES, default=OVERVIEW)
    status = models.BooleanField(default=False,help_text="0-default,1-Hidden")
    
    def __str__(self):
        return f"{self.exam_name} - {self.exam_type}"
    

    
class About_Video(models.Model):
    video_link = models.URLField(max_length=200, unique=True, null=True, blank=True)

    
from django.utils import timezone
from datetime import timedelta

class OTPVerification(models.Model):
    phone = models.CharField(max_length=15)
    otp = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True)

    def is_valid(self):
        return self.created_at >= timezone.now() - timedelta(minutes=5) 


class Enquiry_Submission(models.Model):
    college = models.ForeignKey(CollegeModel, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=15) 
    submitted_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.name} - {self.college.college_name}"

    
class SliderImage(models.Model):
    image = models.ImageField(upload_to='slider_images/')
    caption = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.caption if self.caption else "Slider Image"
    
        
class headerMain(models.Model):
    main_heading = models.CharField(max_length=100)
    
    def __str__(self):
        return self.main_heading 
     
class SubHeader(models.Model):
    main_header = models.ForeignKey(headerMain, on_delete=models.CASCADE)
    sub_header = models.CharField(max_length=100)
    
    def __str__(self):
        return self.sub_header 
  
class SubHeaderHeading(models.Model):
    main_header = models.ForeignKey(headerMain, on_delete=models.CASCADE)
    sub_header = models.ForeignKey(SubHeader, on_delete=models.CASCADE)
    sub_heading = models.CharField(max_length=100)
    
    def __str__(self):
        return self.sub_heading 
    
class HeaderDetails(models.Model):
    sub_heading = models.ForeignKey(SubHeaderHeading, on_delete=models.CASCADE)
    header_image = models.ImageField(upload_to='header_image/')
    details = models.TextField(null=True, blank=True)
    brochure = models.FileField(upload_to='brochure/', null=True, blank=True)
    def __str__(self):
        return self.details
    
class Notification(models.Model):
    message = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)    
    notification_end_date = models.DateTimeField()
    details = models.TextField(null=True, blank=True)
    def is_active(self):
        return self.notification_end_date >= timezone.now()
    
    
class AddOn_Course(models.Model):

templates/admin_pages/add_client_reviews.html
{% extends "admin_pages/base.html" %}
{% load static %}

{% block content %}
      
            <div class="container">
              <div class="row justify-content-center">
                <div class="col-md-6 grid-margin stretch-card">
                  <div class="card">
                    <div class="card-body">
                      <h4 class="card-title">Add Student Reviews</h4>
                      <!-- <p class="card-description">
                        Basic form layout
                      </p> -->
                      <form class="forms-sample" method="POST" enctype="multipart/form-data"> {% csrf_token %}
                        <div class="form-group">
                          <label for="ClientName">Student Name</label>
                          <input type="text" class="form-control" id="ClientName" name="client_name" placeholder="Student Name" required>
                        </div>
                        <div class="form-group">
                          <label for="designation">Designation</label>
                          <input type="text" class="form-control" id="designation" name="designation" placeholder="Designation">
                        </div>
                        <div class="form-group">
                          <label for="review">Review</label>
                          <textarea class="form-control" name="review" id="review" rows="3" style="height: 150px;" placeholder="Enter your Review" oninput="checkCharacterLimit(this)" required></textarea>
                          <span id="character_error" style="color: red; display: none;">Maximum 150 characters allowed</span>
                      </div>
                      
                      <div class="form-group">
                        <label for="imageFile">Student Image</label>
                        <input type="file" class="form-control-file" id="imageFile" name="client_image" accept="image/*">
                    </div>

                    <div class="form-group">
                      <label for="videoFile">Review Video</label>
                      <input type="file" class="form-control-file" id="videoFile" name="review_video" accept="video/*">
                  </div>
                        <div class="form-check form-check-flat form-check-primary">
                          <label class="form-check-label">
                            <!-- <input type="checkbox" class="form-check-input">
                            Remember me -->
                          </label>
                        </div>
                        <button type="submit" class="btn btn-primary me-2">Submit</button>
                        <!-- <button class="btn btn-light">Cancel</button> -->
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <script>
              document.getElementById('product_name').addEventListener('input', function() {
                  var nameInput = this.value;
                  if (nameInput.length > 50) {
                      document.getElementById('name_error').style.display = 'block';
                  } else {
                      document.getElementById('name_error').style.display = 'none';
                  }
              });
          
          
              function checkCharacterLimit(textarea) {
                  var maxLength = 400; // Maximum character limit
                  var currentLength = textarea.value.length;
          
                  if (currentLength > maxLength) {
                      document.getElementById('character_error').style.display = 'block';
                  } else {
                      document.getElementById('character_error').style.display = 'none';
                  }
              }
          </script>
          
            {% endblock %}

templates/admin_pages/add_sub_navbar_list.html
{% extends "admin_pages/base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Add Navbar Item</h4>
                    <form class="forms-sample" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="mainHeading">Main Heading</label>
                            <select name="category" id="id_category" class="form-control" onchange="fetchNavbarItems(this.value)">
                                <option value="">Select a category</option>
                                {% for category in categories %}
                                    <option value="{{ category.id }}">{{ category.category_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="navbarList">Navbar List</label>
                            <select name="list_category" id="id_navbar_list" class="form-control">
                                <option value="">Select a navbar item</option>
                                <!-- This will be populated via AJAX -->
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="newsHeading">Navbar Sub Item</label>
                            <input type="text" class="form-control" id="newsHeading" name="sub_list" placeholder="Navbar list name">
                        </div>
                        <button type="submit" class="btn btn-primary me-2">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
function fetchNavbarItems(categoryId) {
    const navbarListSelect = document.getElementById('id_navbar_list');
    navbarListSelect.innerHTML = '<option value="">Select a navbar item</option>';  // Reset options

    if (categoryId) {
        fetch(`/fetch-navbar-items?category_id=${categoryId}`)
            .then(response => response.json())
            .then(data => {
                data.forEach(item => {
                    const option = document.createElement('option');
                    option.value = item.id;
                    option.textContent = item.list_item;
                    navbarListSelect.appendChild(option);
                });
            })
            .catch(error => console.error('Error fetching navbar items:', error));
    }
}
</script>
{% endblock %}

templates/admin_pages/blog.html
{% extends "admin_pages/base.html" %}
{% load static %}
{% block content %}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Add Blog Details</h4>
          <form class="forms-sample" method="POST" enctype="multipart/form-data"> 
            {% csrf_token %}
            <div class="form-group">
              <div class="input-box">
                <label for="id_category">Blog Category</label>
                <select name="category" id="id_category" class="form-control">
                  {% for category in categories %}
                  <option value="{{ category.id }}">{{ category.category_name }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <div class="form-group">
              <label for="addblogDescription">Blog Description</label>
              <textarea class="form-control" name="blog_description" id="addblogDescription" rows="3" style="height: 150px;" placeholder="Enter Your Description"></textarea>
            </div>
            <div class="form-group">
              <label for="imageFile">Blog Image</label>
              <input type="file" class="form-control-file" id="imageFile" name="blog_image" accept="image/*">
            </div>
            <button type="submit" class="btn btn-primary me-2">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Include CKEditor 5 -->
<!-- Include CKEditor 5 -->
<script src="https://cdn.ckeditor.com/ckeditor5/39.0.0/classic/ckeditor.js"></script>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    ClassicEditor
      .create(document.querySelector('#addblogDescription'), {
        toolbar: [
          'heading', '|',
          'fontFamily', 'fontSize', 'fontColor', 'fontBackgroundColor', '|',
          'bold', 'italic', 'underline', 'strikethrough', '|',
          'link', 'uploadFile', '|',
          'bulletedList', 'numberedList', 'blockQuote', '|',
          'insertTable', 'imageUpload', 'mediaEmbed', '|',
          'undo', 'redo'
        ],
        fontFamily: {
          options: [
            'default',
            'Arial, Helvetica, sans-serif',
            'Courier New, Courier, monospace',
            'Georgia, serif',
            'Lucida Sans Unicode, Lucida Grande, sans-serif',
            'Tahoma, Geneva, sans-serif',
            'Times New Roman, Times, serif',
            'Trebuchet MS, Helvetica, sans-serif',
            'Verdana, Geneva, sans-serif'
          ],
          supportAllValues: true // Ensures all custom font families are supported
        },
        fontSize: {
          options: [
            'tiny',
            'small',
            'default',
            'big',
            'huge'
          ]
        },
        ckfinder: {
          uploadUrl: '{% url "ckeditor_upload" %}'
        },
        simpleUpload: {
          uploadUrl: '{% url "ckeditor_upload" %}',
          headers: {
            'X-CSRFToken': '{{ csrf_token }}'
          }
        }
      })
      .then(editor => {
        console.log('CKEditor initialized successfully.');
      })
      .catch(error => {
        console.error('Error initializing CKEditor:', error);
      });
  });
</script>


{% endblock %}

templates/admin_pages/create_course_subcategory.html
{% extends "admin_pages/base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Create Course SubCategory</h4>
                    <form class="forms-sample" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_course">Course Name</label>
                            <select name="course" id="id_course" class="form-control">
                                <option value="">Select Course</option>
                                {% for course in form.fields.course.queryset %}
                                    <option value="{{ course.id }}">{{ course.course_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="id_sub_course">Sub Course</label>
                            <select name="sub_course" id="id_sub_course" class="form-control">
                                <option value="">Select Sub Course</option>
                                {% for sub_course in form.fields.sub_course.queryset %}
                                    <option value="{{ sub_course.id }}">{{ sub_course }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="id_sub_category_name">Sub Course SubCategory Name</label>
                            <input type="text" name="sub_category_name" id="id_sub_category_name" class="form-control" value="{{ form.sub_category_name.value }}">
                        </div>
                        <button type="submit" class="btn btn-primary me-2">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/admin_pages/create_sub_collection.html
{% extends "admin_pages/base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Create Sub Course</h4>
                    <form class="forms-sample" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        <div class="form-group">
                            <label for="id_course_collection">Course Collection</label>
                            <select name="course" id="id_course_collection" class="form-control">
                                <option value="">Select Course Collection</option>
                                {% for course_collection in course_collections %}
                                    <option value="{{ course_collection.id }}">{{ course_collection }}</option>
                                {% endfor %}
                            </select>
                        </div>
                       
                        <div class="form-group">
                            <label for="id_course_type">Sub Content</label>
                            <select class="form-control" id="id_course_type" name="course_type">
                                {% for value, name in form.fields.course_type.choices %}
                                    <option value="{{ value }}" {% if value == form.fields.course_type.value %}selected{% endif %}>{{ name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary me-2">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        $('#id_course_collection').change(function() {
            var collectionId = $(this).val();
            $.ajax({
                url: '{% url "load_courses" %}',
                data: {
                    'collection': collectionId
                },
                success: function(data) {
                    var options = '<option value="">Select Course</option>';
                    data.forEach(function(course) {
                        options += '<option value="' + course.id + '">' + course.course_name + '</option>';
                    });
                    $('#id_course').html(options);
                }
            });
        });
    });
</script>
{% endblock %}

templates/admin_pages/create_sub_header.html
{% extends "admin_pages/base.html" %}
{% load static %}
{% block content %}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Sub Header</h4>
          <form class="forms-sample" method="POST" enctype="multipart/form-data"> 
            {% csrf_token %}
            <div class="form-group">
              <div class="input-box">
                <label for="id_category">Main Header</label>
                <select name="main_header" id="id_main_header" class="form-control">
                    {% for header in main_headers %}
                    <option value="{{ header.id }}">{{ header.main_heading }}</option>
                    {% endfor %}
                </select>
              </div>
            </div>

            <div class="form-group">
                <label for="subHeader">Sub Heading</label>
                <input type="text" class="form-control" id="subHeader" name="sub_header" placeholder="Sub Heading">
              </div>
            <button type="submit" class="btn btn-primary me-2">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

templates/admin_pages/notification_list.html
{% extends "admin_pages/base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <h2>Sub Courses</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Notification Message</th>
                <th>Date</th>
                <th>Details</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for data in notifications %}
                
                    <tr>
                        <td>{{ data.message }}</td>
                        <td style="width: 600px; height: 200px;  white-space: inherit; word-wrap: break-word;">{{ data.details | safe }}</td>
                        <td>{{ data.notification_end_date }}
                        <td>
                            <a href="{% url 'update_notification' data.pk %}" class="btn btn-primary btn-sm">Update</a>
                            <a href="{% url 'delete_notification' data.pk %}" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this course?');">Delete</a>
                        </td>
                    </tr> 
               
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/admin_pages/view_course_collection.html
{% extends "admin_pages/base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <h2>Sub Courses</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Course Name</th>
                <!-- <th>Course Type</th> -->
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for collection in collections %}
                {% for course in collection.courses.all %}
                    <tr>
                        <td>{{ course.course_name }}</td>
                        <!-- <td>{{ course.get_course_type_display }}</td> -->
                        <td>
                            <a href="{% url 'update_course_collection' collection.id %}" class="btn btn-primary btn-sm">Update</a>
                            <a href="{% url 'delete_course_collection' collection.id %}" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this course?');">Delete</a>
                        </td>
                    </tr> 
                {% endfor %}
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}